project_id = "gicmzzepxupzghcswqyd"

[functions.tiktok-download]
verify_jwt = false

[functions.youtube-download]
verify_jwt = false

[functions.proxy-download]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false


[functions.tiktok-profile]
verify_jwt = false

[functions.pinterest-download]
verify_jwt = false

[functions.serve-robots]
verify_jwt = false

[functions.serve-sitemap]
verify_jwt = false

[functions.telegram-poll]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false
