project_id = "gicmzzepxupzghcswqyd"

[functions.tiktok-download]
verify_jwt = false

[functions.youtube-download]
verify_jwt = false

[functions.facebook-download]
verify_jwt = false

[functions.proxy-download]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false
