// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/download-tiktok.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SUPABASE_URL = "https://gicmzzepxupzghcswqyd.supabase.co";
var ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpY216emVweHVwemdoY3N3cXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NDMxMDAsImV4cCI6MjA4MjAxOTEwMH0.IKH2-7_w4caevftwJ0VNVUAtFiBoOPM3kl6z4O8BjMM";
var download_tiktok_default = defineTool({
  name: "download_tiktok",
  title: "Download TikTok video",
  description: "Get direct download links for a TikTok video (no watermark HD, plus MP3 audio). Accepts any TikTok URL including vt.tiktok.com and vm.tiktok.com short links.",
  inputSchema: {
    url: z.string().url().describe("The TikTok video URL (e.g. https://www.tiktok.com/@user/video/12345).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const res = await fetch(`${SUPABASE_URL}/functions/v1/tiktok-download`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: ANON_KEY,
        Authorization: `Bearer ${ANON_KEY}`
      },
      body: JSON.stringify({ url })
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `TikTok download failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      return { content: [{ type: "text", text }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/download-pinterest.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var SUPABASE_URL2 = "https://gicmzzepxupzghcswqyd.supabase.co";
var ANON_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpY216emVweHVwemdoY3N3cXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NDMxMDAsImV4cCI6MjA4MjAxOTEwMH0.IKH2-7_w4caevftwJ0VNVUAtFiBoOPM3kl6z4O8BjMM";
var download_pinterest_default = defineTool2({
  name: "download_pinterest",
  title: "Download Pinterest video or image",
  description: "Get a direct download link for a Pinterest pin (video or image) in the highest quality available. Accepts pinterest.com pin URLs and pin.it short links.",
  inputSchema: {
    url: z2.string().url().describe("The Pinterest pin URL (e.g. https://pin.it/xxxx or https://www.pinterest.com/pin/12345).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ url }) => {
    const res = await fetch(`${SUPABASE_URL2}/functions/v1/pinterest-download`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: ANON_KEY2,
        Authorization: `Bearer ${ANON_KEY2}`
      },
      body: JSON.stringify({ url })
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Pinterest download failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      return { content: [{ type: "text", text }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/tiktok-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var SUPABASE_URL3 = "https://gicmzzepxupzghcswqyd.supabase.co";
var ANON_KEY3 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpY216emVweHVwemdoY3N3cXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NDMxMDAsImV4cCI6MjA4MjAxOTEwMH0.IKH2-7_w4caevftwJ0VNVUAtFiBoOPM3kl6z4O8BjMM";
var tiktok_profile_default = defineTool3({
  name: "list_tiktok_profile_videos",
  title: "List TikTok profile videos",
  description: "Fetch a list of recent public videos for a TikTok profile (up to ~30). Useful for batch downloading. Accepts a @username or a full profile URL.",
  inputSchema: {
    username: z3.string().min(1).describe("TikTok username (with or without @), or a full profile URL like https://www.tiktok.com/@user.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ username }) => {
    const res = await fetch(`${SUPABASE_URL3}/functions/v1/tiktok-profile`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: ANON_KEY3,
        Authorization: `Bearer ${ANON_KEY3}`
      },
      body: JSON.stringify({ username })
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Profile fetch failed (${res.status}): ${text}` }],
        isError: true
      };
    }
    let data;
    try {
      data = JSON.parse(text);
    } catch {
      return { content: [{ type: "text", text }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "anytt-cc-mcp",
  title: "Anytt.cc Downloader",
  version: "0.1.0",
  instructions: "Tools for Anytt.cc, a free TikTok and Pinterest downloader. Use `download_tiktok` to get no-watermark HD video and MP3 links from a TikTok URL, `download_pinterest` to get direct media links from a Pinterest pin, and `list_tiktok_profile_videos` to enumerate a public TikTok profile's recent videos for batch downloading.",
  tools: [download_tiktok_default, download_pinterest_default, tiktok_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
